---

kind: pipeline
type: docker
name: FullBuild

platform:
  os: linux
  arch: amd64

steps:
- name: Prepare tags
  image: alpine
  commands:
    - borgmatic_ver=$(grep 'borgmatic' requirements.txt | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
    - borg_ver=$(grep 'borgbackup' requirements.txt | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
    - echo "latest" > .tags
    - echo "$${borgmatic_ver}-$${borg_ver}" >> .tags
    - echo "Tags to publish:" && cat .tags

- name: FullBuild
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/borgmatic-docker
    purge: true
    build_args: BUILDKIT_INLINE_CACHE=1
    cache_from: modem7/borgmatic-docker:latest
    dockerfile: Dockerfile
    context: .
    platforms:
      - linux/amd64
      - linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags_file: .tags

- name: pushrm-dockerhub
  image: chko/docker-pushrm
  when:
    status:
      - success
  environment:
    DOCKER_USER:
      from_secret: docker_username
    DOCKER_PASS:
      from_secret: docker_password
    PUSHRM_FILE: README.md
    PUSHRM_SHORT: Multiarch Borgmatic Docker image with S6 overlay, Apprise notifications, and optional Docker CLI
    PUSHRM_TARGET: modem7/borgmatic-docker

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
    - custom
