#!/usr/bin/with-contenv bash

# Install DockerCLI if true
if [ "${DOCKERCLI}" == "true" ]; then
  echo "[custom-init] Installing Docker CLI and Compose..."
  apk add -U --quiet docker-cli docker-cli-compose
fi

# Install additional packages
if [ -v EXTRA_PKGS ]
then
    echo "[custom-init] Installing extra packages: $EXTRA_PKGS"
    apk add -U --quiet $EXTRA_PKGS
fi